//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vp_webservice_dotnet_sample.vp_webservice_auth {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Auth/v3/")]
    public partial class Authorization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Auth/v3/")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Auth/v3/", ConfigurationName="vp_webservice_auth.Auth")]
    public interface Auth {
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_auth.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_auth.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sessionId")]
        vp_webservice_dotnet_sample.vp_webservice_auth.loginResponse login(vp_webservice_dotnet_sample.vp_webservice_auth.login request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_auth.loginResponse> loginAsync(vp_webservice_dotnet_sample.vp_webservice_auth.login request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Auth/v3/", IsWrapped=true)]
    public partial class login {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Auth/v3/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Auth/v3/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public login() {
        }
        
        public login(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Auth/v3/", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Auth/v3/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        public loginResponse() {
        }
        
        public loginResponse(string sessionId) {
            this.sessionId = sessionId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthChannel : vp_webservice_dotnet_sample.vp_webservice_auth.Auth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthClient : System.ServiceModel.ClientBase<vp_webservice_dotnet_sample.vp_webservice_auth.Auth>, vp_webservice_dotnet_sample.vp_webservice_auth.Auth {
        
        public AuthClient() {
        }
        
        public AuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_dotnet_sample.vp_webservice_auth.loginResponse vp_webservice_dotnet_sample.vp_webservice_auth.Auth.login(vp_webservice_dotnet_sample.vp_webservice_auth.login request) {
            return base.Channel.login(request);
        }
        
        public string login(string username, string password) {
            vp_webservice_dotnet_sample.vp_webservice_auth.login inValue = new vp_webservice_dotnet_sample.vp_webservice_auth.login();
            inValue.username = username;
            inValue.password = password;
            vp_webservice_dotnet_sample.vp_webservice_auth.loginResponse retVal = ((vp_webservice_dotnet_sample.vp_webservice_auth.Auth)(this)).login(inValue);
            return retVal.sessionId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_auth.loginResponse> vp_webservice_dotnet_sample.vp_webservice_auth.Auth.loginAsync(vp_webservice_dotnet_sample.vp_webservice_auth.login request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_auth.loginResponse> loginAsync(string username, string password) {
            vp_webservice_dotnet_sample.vp_webservice_auth.login inValue = new vp_webservice_dotnet_sample.vp_webservice_auth.login();
            inValue.username = username;
            inValue.password = password;
            return ((vp_webservice_dotnet_sample.vp_webservice_auth.Auth)(this)).loginAsync(inValue);
        }
    }
}
