//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vp_webservice_dotnet_sample.vp_webservice_documenttasks {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/")]
    public partial class Authorization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/")]
    public partial class DocumentQueueEntryInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long documentQueueEntryIdField;
        
        private long queueIdField;
        
        private long documenIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentQueueEntryId {
            get {
                return this.documentQueueEntryIdField;
            }
            set {
                this.documentQueueEntryIdField = value;
                this.RaisePropertyChanged("documentQueueEntryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long queueId {
            get {
                return this.queueIdField;
            }
            set {
                this.queueIdField = value;
                this.RaisePropertyChanged("queueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documenId {
            get {
                return this.documenIdField;
            }
            set {
                this.documenIdField = value;
                this.RaisePropertyChanged("documenId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/")]
    public partial class InvalidArgument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", ConfigurationName="vp_webservice_documenttasks.DocumentTasks")]
    public interface DocumentTasks {
        
        // CODEGEN: Parameter 'documentQueueInformation' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_documenttasks.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_documenttasks.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_documenttasks.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="documentQueueInformation")]
        vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueueResponse getNextDocumentInTaskQueue(vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueue request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueueResponse> getNextDocumentInTaskQueueAsync(vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueue request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_documenttasks.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_documenttasks.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_documenttasks.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFailResponse setDocumentProcessedInTaskQueueFail(vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFailResponse> setDocumentProcessedInTaskQueueFailAsync(vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFail request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_documenttasks.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_documenttasks.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_dotnet_sample.vp_webservice_documenttasks.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccessResponse setDocumentProcessedInTaskQueueSuccess(vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccess request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccessResponse> setDocumentProcessedInTaskQueueSuccessAsync(vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccess request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNextDocumentInTaskQueue", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", IsWrapped=true)]
    public partial class getNextDocumentInTaskQueue {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queueName;
        
        public getNextDocumentInTaskQueue() {
        }
        
        public getNextDocumentInTaskQueue(string sessionId, string queueName) {
            this.sessionId = sessionId;
            this.queueName = queueName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNextDocumentInTaskQueueResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", IsWrapped=true)]
    public partial class getNextDocumentInTaskQueueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentQueueEntryInformation documentQueueInformation;
        
        public getNextDocumentInTaskQueueResponse() {
        }
        
        public getNextDocumentInTaskQueueResponse(vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentQueueEntryInformation documentQueueInformation) {
            this.documentQueueInformation = documentQueueInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDocumentProcessedInTaskQueueFail", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", IsWrapped=true)]
    public partial class setDocumentProcessedInTaskQueueFail {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long queueEntryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMessage;
        
        public setDocumentProcessedInTaskQueueFail() {
        }
        
        public setDocumentProcessedInTaskQueueFail(string sessionId, long queueEntryId, string errorMessage) {
            this.sessionId = sessionId;
            this.queueEntryId = queueEntryId;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDocumentProcessedInTaskQueueFailResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", IsWrapped=true)]
    public partial class setDocumentProcessedInTaskQueueFailResponse {
        
        public setDocumentProcessedInTaskQueueFailResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDocumentProcessedInTaskQueueSuccess", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", IsWrapped=true)]
    public partial class setDocumentProcessedInTaskQueueSuccess {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long queueEntryId;
        
        public setDocumentProcessedInTaskQueueSuccess() {
        }
        
        public setDocumentProcessedInTaskQueueSuccess(string sessionId, long queueEntryId) {
            this.sessionId = sessionId;
            this.queueEntryId = queueEntryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDocumentProcessedInTaskQueueSuccessResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/DocumentTasks/v1/", IsWrapped=true)]
    public partial class setDocumentProcessedInTaskQueueSuccessResponse {
        
        public setDocumentProcessedInTaskQueueSuccessResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentTasksChannel : vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentTasksClient : System.ServiceModel.ClientBase<vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks>, vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks {
        
        public DocumentTasksClient() {
        }
        
        public DocumentTasksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentTasksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentTasksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentTasksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueueResponse vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks.getNextDocumentInTaskQueue(vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueue request) {
            return base.Channel.getNextDocumentInTaskQueue(request);
        }
        
        public vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentQueueEntryInformation getNextDocumentInTaskQueue(string sessionId, string queueName) {
            vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueue inValue = new vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueue();
            inValue.sessionId = sessionId;
            inValue.queueName = queueName;
            vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueueResponse retVal = ((vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks)(this)).getNextDocumentInTaskQueue(inValue);
            return retVal.documentQueueInformation;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueueResponse> vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks.getNextDocumentInTaskQueueAsync(vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueue request) {
            return base.Channel.getNextDocumentInTaskQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueueResponse> getNextDocumentInTaskQueueAsync(string sessionId, string queueName) {
            vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueue inValue = new vp_webservice_dotnet_sample.vp_webservice_documenttasks.getNextDocumentInTaskQueue();
            inValue.sessionId = sessionId;
            inValue.queueName = queueName;
            return ((vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks)(this)).getNextDocumentInTaskQueueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFailResponse vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks.setDocumentProcessedInTaskQueueFail(vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFail request) {
            return base.Channel.setDocumentProcessedInTaskQueueFail(request);
        }
        
        public void setDocumentProcessedInTaskQueueFail(string sessionId, long queueEntryId, string errorMessage) {
            vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFail inValue = new vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFail();
            inValue.sessionId = sessionId;
            inValue.queueEntryId = queueEntryId;
            inValue.errorMessage = errorMessage;
            vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFailResponse retVal = ((vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks)(this)).setDocumentProcessedInTaskQueueFail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFailResponse> vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks.setDocumentProcessedInTaskQueueFailAsync(vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFail request) {
            return base.Channel.setDocumentProcessedInTaskQueueFailAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFailResponse> setDocumentProcessedInTaskQueueFailAsync(string sessionId, long queueEntryId, string errorMessage) {
            vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFail inValue = new vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueFail();
            inValue.sessionId = sessionId;
            inValue.queueEntryId = queueEntryId;
            inValue.errorMessage = errorMessage;
            return ((vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks)(this)).setDocumentProcessedInTaskQueueFailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccessResponse vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks.setDocumentProcessedInTaskQueueSuccess(vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccess request) {
            return base.Channel.setDocumentProcessedInTaskQueueSuccess(request);
        }
        
        public void setDocumentProcessedInTaskQueueSuccess(string sessionId, long queueEntryId) {
            vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccess inValue = new vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccess();
            inValue.sessionId = sessionId;
            inValue.queueEntryId = queueEntryId;
            vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccessResponse retVal = ((vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks)(this)).setDocumentProcessedInTaskQueueSuccess(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccessResponse> vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks.setDocumentProcessedInTaskQueueSuccessAsync(vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccess request) {
            return base.Channel.setDocumentProcessedInTaskQueueSuccessAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccessResponse> setDocumentProcessedInTaskQueueSuccessAsync(string sessionId, long queueEntryId) {
            vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccess inValue = new vp_webservice_dotnet_sample.vp_webservice_documenttasks.setDocumentProcessedInTaskQueueSuccess();
            inValue.sessionId = sessionId;
            inValue.queueEntryId = queueEntryId;
            return ((vp_webservice_dotnet_sample.vp_webservice_documenttasks.DocumentTasks)(this)).setDocumentProcessedInTaskQueueSuccessAsync(inValue);
        }
    }
}
